$out = Join-Path (Get-Location) 'Dokumentasi_dan_RAB_Smart_Finder.doc'
$html = @'
<!DOCTYPE html><html><head><meta charset="utf-8"><title>Dokumentasi dan RAB Smart Finder</title>
<style>
body{font-family:Arial,sans-serif;font-size:10.5pt;line-height:1.45;color:#172033;margin:36pt}h1{color:#123b67;border-bottom:2px solid #2f75b5;padding-bottom:5px;font-size:18pt}h2{color:#1f5c91;font-size:13pt;margin-top:18pt}h3{color:#365f91;font-size:11pt}table{border-collapse:collapse;width:100%;margin:8pt 0 14pt}th{background:#1f4e78;color:white}td,th{border:1px solid #9aa9b8;padding:5px;vertical-align:top}ul,ol{margin-top:3pt}.cover{text-align:center;margin-top:150pt}.cover h1{border:0;font-size:28pt}.note{background:#eef5fb;border-left:4px solid #2f75b5;padding:8px}.small{font-size:9pt;color:#52606d}a{color:#0563c1}
</style></head><body>
<div class="cover"><h1>SMART FINDER</h1><h2>Dokumentasi Fitur, Arsitektur Data,<br>Perhitungan SES, dan RAB Implementasi</h2><p>Untuk survey kelayakan cabang Bimba &amp; Preschool</p><p>20 September 2026</p></div><br clear="all" style="page-break-before:always">
<h1>1. Ringkasan Eksekutif</h1>
<p>Smart Finder adalah dashboard geospasial untuk menilai kelayakan pembukaan cabang baru. Aplikasi menggabungkan POI, demografi Dukcapil, peta CGIS, nilai tanah, penggunaan tanah, Hak Milik, kawasan kumuh, analisis SES, dan Potensi Area.</p>
<p>Output utamanya adalah peta interaktif radius 3 km, profil demografi, hasil studi kelayakan, indeks SES, indeks Potensi Area, dan grid hexagon radius 1,5 km untuk membandingkan kandidat area.</p>
<div class="note"><b>Catatan model:</b> SES saat ini adalah indeks operasional/provisional. Nilainya bersifat relatif terhadap wilayah pembanding dan bukan klasifikasi SES ekonomi resmi pemerintah.</div>
<h1>2. Detail Fitur Aplikasi</h1>
<h2>2.1 Input lokasi dan parameter</h2><ul><li>Input alamat, koordinat, atau tautan Google Maps.</li><li>Reverse geocoding dan pencarian alamat dengan ArcGIS, dengan fallback OpenStreetMap.</li><li>Radius analisis 3 km.</li><li>Marker titik lokasi dan lingkaran radius.</li><li>Mode peta 2D dan satellite.</li></ul>
<h2>2.2 POI dan market mapping</h2><ul><li>Crawling/pencarian POI sekitar lokasi.</li><li>Sumber: Google Maps crawler, OpenStreetMap/Overpass, Google Places, dan ArcGIS Places jika diaktifkan.</li><li>Kategori pendukung, risiko, kompetitor, pendidikan, hunian, fasilitas keluarga, dan lainnya.</li><li>Marker interaktif dengan nama, alamat, rating, ulasan, tautan peta, kategori, dan sumber.</li><li>Heatmap, ringkasan POI, filter sumber, dan export XLS.</li></ul>
<h2>2.3 Analisis studi kelayakan</h2><ul><li>TAM, SAM, SOM, market share, estimasi kapasitas siswa, kompetitor, SWOT, peluang, risiko, dan rekomendasi.</li><li>Skenario SPP/biaya dan pembacaan kapasitas cabang.</li><li>Riset web, berita, media sosial, event, dan sinyal pasar melalui modul riset bila dikonfigurasi.</li></ul>
<h2>2.4 Rekomendasi Area</h2><ul><li>Dropdown provinsi, kota/kabupaten multi-select, dan kecamatan multi-select.</li><li>Opsi pilih semua kecamatan dan pencarian wilayah.</li><li>Perhitungan SES wilayah pembanding.</li><li>Grid hexagon radius 1,5 km.</li><li>Grid dasar langsung tampil; enrichment BIG/BHUMI berjalan progresif.</li><li>Progress per hexagon, warna SES, popup skor, confidence, komponen, dan sumber data.</li></ul>
<h2>2.5 CGIS dan demografi</h2><ul><li>Polygon demografi Dukcapil dengan klasifikasi warna biru rendah sampai merah tinggi.</li><li>Jumlah penduduk, kelompok usia u0-u4, u5-u9, usia 0-14, produktif 15-64, dan lansia 65+.</li><li>Proporsi anak, kelahiran 2020-2024, pertumbuhan penduduk, dan rata-rata lama sekolah bila tersedia.</li><li>Layer nilai tanah dengan dua opsi: BHUMI WMS dan JSON BIG.</li></ul>
<h2>2.6 Pertanahan dan lingkungan</h2><ul><li>BIG ZNT JSON: range nilai, kelas nilai, zona, kanwil, dan kantah.</li><li>BIG Penggunaan Tanah 10K: objek penggunaan tanah, kode, dan luas/atribut terkait.</li><li>BIG Hak Milik: polygon bidang, tipe hak, NIB, kecamatan, dan kelurahan pada provinsi tersedia.</li><li>BIG kawasan kumuh: polygon dan atribut wilayah, RT/RW, SK, dan keterangan.</li><li>JSON BIG menjadi prioritas; BHUMI/CSW menjadi fallback jika data BIG kosong.</li></ul>
<h2>2.7 Fitur pendukung</h2><ul><li>BPS Data Explorer.</li><li>Instagram Locator.</li><li>Live CCTV Indonesia.</li><li>Shortlist referensi ruko/cabang.</li><li>Draw/tactical map tools.</li><li>Hard reset, spinner loading, log progres, dan export.</li></ul>
<h1>3. Arsitektur dan Alur Data</h1>
<table><tr><th>Komponen</th><th>Fungsi</th></tr><tr><td>Frontend HTML/JavaScript</td><td>UI, drawer, peta, popup, layer, progress, dan export XLS.</td></tr><tr><td>Node.js server</td><td>API routing, proxy, crawling, cache, enrichment, dan startup port 3000.</td></tr><tr><td>SES engine</td><td>Ekstraksi indikator, normalisasi p05-p95, bobot domain, confidence, dan kelas.</td></tr><tr><td>Dukcapil ArcGIS</td><td>Polygon wilayah dan atribut demografi.</td></tr><tr><td>BIG ArcGIS REST JSON</td><td>ZNT, penggunaan tanah, Hak Milik, dan kawasan kumuh.</td></tr><tr><td>BHUMI ATR/BPN</td><td>WMS dan fallback identify pertanahan.</td></tr><tr><td>Google/ArcGIS services</td><td>Geocode, route, places, dan enrichment.</td></tr><tr><td>Database/cache</td><td>Disarankan menyimpan cache wilayah, POI, request log, dan hasil enrichment.</td></tr></table>
<h2>3.1 Urutan perhitungan rekomendasi</h2><ol><li>Pengguna memilih provinsi, kota/kabupaten, dan kecamatan.</li><li>Sistem mengambil polygon Dukcapil.</li><li>SES dasar dihitung.</li><li>Grid hexagon 1,5 km dibuat dan langsung ditampilkan.</li><li>JSON BIG mengambil ZNT, guna tanah, Hak Milik, dan kawasan kumuh per hexagon.</li><li>Jika BIG kosong, BHUMI/CSW menjadi fallback.</li><li>Semua data digabung dan SES/Potensi Area dihitung ulang.</li><li>Peta, warna, popup, dan coverage diperbarui.</li></ol>
<h1>4. Perhitungan SES dan Potensi Area</h1>
<p>Normalisasi indikator menggunakan pembanding wilayah yang sedang diproses dengan batas p05-p95 untuk mengurangi outlier. Indikator positif semakin tinggi semakin baik; indikator lower-is-higher dibalik.</p>
<h2>4.1 Bobot domain SES</h2><table><tr><th>Domain</th><th>Bobot</th></tr><tr><td>Economic capacity</td><td>35%</td></tr><tr><td>Education</td><td>20%</td></tr><tr><td>Employment</td><td>15%</td></tr><tr><td>Household &amp; housing</td><td>15%</td></tr><tr><td>Consumption</td><td>10%</td></tr><tr><td>Demography</td><td>5%</td></tr></table>
<h2>4.2 Indikator utama</h2><ul><li>Pendidikan: SLTA+, diploma+, S1+, master/doctoral bila tersedia.</li><li>Pekerjaan: profesional/terampil, usaha/perdagangan, dan belum/tidak bekerja.</li><li>Hunian: ukuran rumah tangga, kepemilikan rumah bila tersedia, dan Hak Milik.</li><li>Nilai tanah ZNT sebagai proxy ekonomi/lokasi, bukan pengganti pendapatan.</li><li>Demografi: anak 0-14, usia produktif 15-64, lansia 65+.</li><li>Kawasan kumuh BIG menjadi faktor pengurang hunian dan area.</li></ul>
<h2>4.3 Bobot Potensi Area</h2><table><tr><th>Domain</th><th>Bobot</th></tr><tr><td>Target demand anak</td><td>27%</td></tr><tr><td>Child share</td><td>18%</td></tr><tr><td>Population</td><td>9%</td></tr><tr><td>Tenure security</td><td>9%</td></tr><tr><td>Residential density</td><td>14%</td></tr><tr><td>Land market</td><td>10%</td></tr><tr><td>Birth signal</td><td>8%</td></tr><tr><td>Growth signal</td><td>5%</td></tr><tr><td>Risk adjustment</td><td>5%</td></tr></table>
<p><b>Confidence</b> menunjukkan cakupan indikator yang benar-benar tersedia. Confidence rendah berarti hasil harus divalidasi dengan survei lapangan.</p>
<br clear="all" style="page-break-before:always">
<h1>5. RAB Operasional</h1>
<p>Catatan penting: angka <b>5.000 pada komponen API adalah kuota standar 5.000 panggilan API per bulan, bukan harga Rp5.000</b>. Biaya API dihitung berdasarkan SKU, tarif resmi penyedia, free cap, jumlah request, paging, dan fitur yang digunakan.</p>
<table><tr><th>No</th><th>Komponen</th><th>Standar kuota / anggaran</th></tr><tr><td>1</td><td>VPS Hostinger</td><td>Rp5.000 (anggaran internal)</td></tr><tr><td>2</td><td>Database Hostinger</td><td>Rp5.000 (anggaran internal)</td></tr><tr><td>3</td><td>Backup offsite</td><td>Rp5.000 (anggaran internal)</td></tr><tr><td>4</td><td>Monitoring dan alert</td><td>Rp5.000 (anggaran internal)</td></tr><tr><td>5</td><td>Google Maps Platform: Places, Geocode, Routes, dan Maps</td><td><b>5.000 panggilan API/bulan</b>; biaya mengikuti SKU dan tarif resmi</td></tr><tr><td>6</td><td>ArcGIS: Geocoding, Places, Routing, GeoEnrichment</td><td><b>5.000 panggilan API/bulan</b>; biaya mengikuti layanan dan tarif resmi</td></tr><tr><td>7</td><td>Domain dan SSL</td><td>Rp5.000 (anggaran internal)</td></tr><tr><td colspan="2"><b>Subtotal komponen non-API</b></td><td><b>Rp25.000/bulan</b></td></tr><tr><td colspan="2"><b>Biaya API</b></td><td><b>Dihitung terpisah sesuai pemakaian dan tarif resmi</b></td></tr></table>
<p>Kuota 5.000 panggilan API adalah batas perencanaan awal per layanan, bukan jaminan bahwa biaya bulanannya Rp5.000. Gunakan quota limit, cache, dan budget alert agar pemakaian serta tagihan aktual dapat dipantau.</p>
<h2>5.1 Referensi komponen Google Maps Platform</h2><p>Komponen yang perlu disiapkan: Dynamic Maps/Map Tiles, Geocoding, Places Text Search/Nearby Search, Place Details, Routes Compute Routes, Route Matrix, dan opsional Roads/Street View. Tarif resmi tetap pay-as-you-go.</p><table><tr><th>SKU</th><th>Harga setelah free cap</th><th>Free cap/bulan</th><th>Estimasi 5.000 panggilan</th></tr><tr><td>Dynamic Maps</td><td>US$7/1.000 load</td><td>10.000</td><td>US$0 / Rp0</td></tr><tr><td>Geocoding</td><td>US$5/1.000 request</td><td>10.000</td><td>US$0 / Rp0</td></tr><tr><td>Routes Essentials</td><td>US$5/1.000 request</td><td>10.000</td><td>US$0 / Rp0</td></tr><tr><td>Route Matrix Essentials</td><td>US$5/1.000 request</td><td>10.000</td><td>US$0 / Rp0</td></tr><tr><td>Places Text Search Pro</td><td>US$32/1.000 request</td><td>5.000</td><td>US$0 / Rp0</td></tr><tr><td>Places Nearby Search Pro</td><td>US$32/1.000 request</td><td>5.000</td><td>US$0 / Rp0</td></tr><tr><td>Place Details Pro</td><td>US$17/1.000 request</td><td>5.000</td><td>US$0 / Rp0</td></tr></table><p><b>Estimasi Google Maps:</b> untuk 5.000 panggilan pada masing-masing SKU di atas, biaya pemakaian diperkirakan <b>US$0/Rp0</b> karena masih berada dalam free cap. Tarif berlaku jika kuota gratis terlampaui.</p>
<h2>5.2 Referensi komponen ArcGIS Location Platform</h2><table><tr><th>Layanan</th><th>Tarif relevan</th><th>Estimasi 5.000 panggilan</th></tr><tr><td>Geocoding tidak tersimpan</td><td>20.000 gratis, lalu US$0,50/1.000 geocodes</td><td>US$0 / Rp0</td></tr><tr><td>Routing</td><td>20.000 gratis, lalu US$0,50/1.000 routes</td><td>US$0 / Rp0</td></tr><tr><td>GeoEnrichment attributes</td><td>US$1/1.000 attribute values</td><td>1 atribut/request: US$5 / sekitar Rp89.000; 10 atribut/request: US$50 / sekitar Rp887.000</td></tr><tr><td>Places search</td><td>500 gratis, lalu US$8/1.000 searches</td><td>US$36 / sekitar Rp639.000</td></tr><tr><td>Place attributes</td><td>100 gratis, lalu US$0,05/1.000 places</td><td>sekitar US$0,25 / sekitar Rp5.000</td></tr><tr><td>Address attributes</td><td>100 gratis, lalu US$0,10/1.000 places</td><td>sekitar US$0,49 / sekitar Rp9.000</td></tr><tr><td>Service areas</td><td>5.000 gratis, lalu US$50/1.000</td><td>US$0 / Rp0</td></tr></table><p><b>Estimasi ArcGIS:</b> sekitar <b>Rp650.000-Rp1.000.000/bulan</b> untuk skenario yang memakai Places Search dan GeoEnrichment. GeoEnrichment dihitung berdasarkan jumlah nilai atribut yang dikembalikan, bukan hanya jumlah request.</p>
<h2>5.3 Ringkasan RAB operasional</h2><table><tr><th>Komponen</th><th>Kuota / dasar perhitungan</th><th>Estimasi biaya</th></tr><tr><td>Infrastruktur non-API</td><td>5 komponen anggaran internal</td><td><b>Rp25.000/bulan</b></td></tr><tr><td>Google Maps Platform</td><td><b>5.000 panggilan API per SKU/bulan</b></td><td><b>Rp0</b> selama masih dalam free cap</td></tr><tr><td>ArcGIS Location Platform</td><td><b>5.000 panggilan API per layanan/bulan</b></td><td><b>Rp650.000-Rp1.000.000/bulan</b></td></tr><tr><td><b>Plafon gabungan API yang disarankan</b></td><td>Google Maps + ArcGIS</td><td><b>Sekitar Rp1.500.000/bulan</b></td></tr></table><p>Perhitungan menggunakan kurs kerja JISDOR <b>Rp17.745/USD</b>. Estimasi belum memasukkan pajak, biaya kartu, perubahan tarif, pemakaian di luar kuota, paging, field tambahan, atau SKU lain.</p>
<h1>7. Rekomendasi Deployment Produksi</h1><ol><li>Gunakan KVM 2 untuk pilot; naik ke KVM 4 jika crawling/enrichment paralel meningkat.</li><li>Pasang Nginx, HTTPS, firewall, fail2ban, PM2/systemd, dan log rotation.</li><li>Simpan API key hanya di environment server dan batasi quota/referrer/IP.</li><li>Gunakan Redis atau cache persistent untuk geocode, POI, BIG, BHUMI, dan Dukcapil.</li><li>Gunakan job queue agar pengguna tidak menunggu seluruh crawling/enrichment.</li><li>Aktifkan backup database harian dan backup offsite mingguan.</li><li>Aktifkan budget alert Google Cloud dan ArcGIS.</li><li>UAT dengan Banten, Jawa Barat, Jakarta, dan satu kota luar Jabodetabek.</li><li>Validasi hasil skor dengan survei lapangan sebelum keputusan investasi final.</li></ol>
<h1>8. Batasan dan Risiko</h1><ul><li>SES provisional dan bukan pengganti pendapatan rumah tangga.</li><li>ZNT adalah proxy lokasi dan tidak selalu sama dengan harga transaksi.</li><li>Cakupan Hak Milik BIG berbeda per provinsi dan tidak mencakup seluruh jenis hak.</li><li>Endpoint pemerintah dapat berubah schema, rate limit, sertifikat, atau downtime.</li><li>Google dan ArcGIS memiliki batas penyimpanan serta terms penggunaan data.</li><li>Crawling Google Maps rentan terhadap perubahan halaman dan perlu tinjauan legal.</li><li>Kawasan kumuh perlu ditingkatkan menjadi persentase luas polygon agar lebih presisi.</li><li>Biaya API aktual ditentukan oleh request, paging, fitur, dan attribute values.</li></ul>
<h1>9. Referensi Resmi</h1><ul><li><a href="https://www.hostinger.com/id/hosting-vps">Hostinger VPS</a></li><li><a href="https://developers.google.com/maps/billing-and-pricing/pricing">Google Maps Platform pricing</a></li><li><a href="https://developers.google.com/maps/billing-and-pricing/manage-costs">Google cost management</a></li><li><a href="https://developers.arcgis.com/rest/geocode/">ArcGIS Geocoding</a></li><li><a href="https://developers.arcgis.com/rest/routing/">ArcGIS Routing</a></li><li><a href="https://developers.arcgis.com/rest/geoenrichment/">ArcGIS GeoEnrichment</a></li><li><a href="https://developers.arcgis.com/rest/places/">ArcGIS Places</a></li><li><a href="https://www.bi.go.id/id/statistik/informasi-kurs/jisdor/Default.aspx">JISDOR Bank Indonesia</a></li></ul>
<p class="small">Dokumen disusun berdasarkan source code Smart Finder dan harga publik yang diakses pada September 2026.</p>
</body></html>
'@
Set-Content -LiteralPath $out -Value $html -Encoding UTF8
Write-Output $out
