/**
 * SES configuration.
 *
 * The active model is still provisional because the current payload does not
 * contain verified income, poverty, housing-quality, asset, or consumption
 * indicators. Missing domains are not silently converted to zero.
 */
module.exports = {
  version: "ses-dukcapil-composite-v6-oecd-p95-preschool",
  status: "provisional",
  label: "SES Provisional - Dukcapil + ATR/BPN tenure, education, employment, household proxy, and age profile",
  maxConfidence: 35,
  referencePeriod: "Dukcapil polygon payload; period follows the source",
  classes: {
    A: { min: 60, label: "Relatif lebih tinggi" },
    B: { min: 40, label: "Relatif menengah" },
    C: { min: 0, label: "Relatif lebih rendah" },
  },
  // Smartfinder internal weights; these are not an official government SES standard.
  domainWeights: {
    economic_capacity: 0.35,
    education: 0.20,
    employment: 0.15,
    household_housing: 0.15,
    consumption: 0.10,
    demography: 0.05,
  },
  // Separate market-fit score. These indicators are not silently treated as SES.
  areaPotentialWeights: {
    target_demand: 0.27,
    child_share: 0.18,
    population: 0.09,
    tenure_security: 0.09,
    residential_density: 0.14,
    land_market: 0.10,
    birth_signal: 0.08,
    growth_signal: 0.05,
    risk_adjustment: 0.05,
  },
  areaPotentialIndicators: [
    { id: "target_children_0_5_proxy", label: "Estimasi anak usia 0–5", domain: "target_demand", weight: 0.70, direction: "positive", unit: "orang" },
    { id: "child_share", label: "Proporsi anak usia 0–14", domain: "child_share", weight: 1, direction: "positive", unit: "%" },
    { id: "population", label: "Jumlah penduduk", domain: "population", weight: 1, direction: "positive", unit: "orang" },
    { id: "freehold_share", label: "Proporsi hak milik", domain: "tenure_security", weight: 1, direction: "positive", unit: "%" },
    { id: "dense_residential_share", label: "Proporsi perumahan padat (indikator wilayah)", domain: "residential_density", weight: 0.35, direction: "positive", unit: "%" },
    { id: "bhumi_formal_residential_share", label: "Proporsi perumahan formal/padat BHUMI", domain: "residential_density", weight: 0.65, direction: "positive", unit: "%" },
    { id: "bhumi_land_value_average", label: "Nilai tanah BHUMI", domain: "land_market", weight: 1, direction: "positive", unit: "rupiah" },
    { id: "birth_count_2020_2024", label: "Jumlah kelahiran 2020-2024", domain: "birth_signal", weight: 1, direction: "positive", unit: "orang" },
    { id: "population_growth_average", label: "Rata-rata pertumbuhan penduduk", domain: "growth_signal", weight: 1, direction: "positive", unit: "%" },
    { id: "big_slum_presence", label: "Kehadiran kawasan kumuh BIG", domain: "risk_adjustment", weight: 1, direction: "lower_is_higher_signal", unit: "%" },
  ],
  indicators: [
    {
      id: "per_capita_expenditure",
      label: "Pengeluaran per kapita",
      domain: "economic_capacity",
      weight: 0.60,
      direction: "positive",
      unit: "rupiah/kapita",
    },
    {
      id: "poverty_rate",
      label: "Persentase kemiskinan",
      domain: "economic_capacity",
      weight: 0.40,
      direction: "lower_is_higher_signal",
      unit: "%",
    },
    {
      id: "bhumi_land_value_average",
      label: "Nilai tanah BHUMI",
      domain: "economic_capacity",
      weight: 0.45,
      direction: "positive",
      unit: "rupiah",
    },
    {
      id: "average_schooling",
      label: "Rata-rata lama sekolah",
      domain: "education",
      weight: 0.20,
      direction: "positive",
      unit: "tahun",
    },
    {
      id: "household_size",
      label: "Rata-rata ukuran rumah tangga",
      domain: "household_housing",
      weight: 1,
      direction: "lower_is_higher_signal",
      unit: "orang/KK",
    },
    {
      id: "pct_high_school_plus",
      label: "Persentase SLTA atau lebih",
      domain: "education",
      weight: 0.55,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_bachelor_plus",
      label: "Persentase diploma/S1/S2/S3",
      domain: "education",
      weight: 0.45,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_professional_skilled",
      label: "Persentase pekerjaan profesional/terampil",
      domain: "employment",
      weight: 0.45,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_business",
      label: "Persentase usaha/perdagangan",
      domain: "employment",
      weight: 0.25,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_unemployed",
      label: "Persentase belum/tidak bekerja",
      domain: "employment",
      weight: 0.30,
      direction: "lower_is_higher_signal",
      unit: "%",
    },
    {
      id: "unemployment_rate",
      label: "Tingkat pengangguran terbuka",
      domain: "employment",
      weight: 0.20,
      direction: "lower_is_higher_signal",
      unit: "%",
    },
    {
      id: "home_ownership_share",
      label: "Kepemilikan rumah",
      domain: "household_housing",
      weight: 0.60,
      direction: "positive",
      unit: "%",
    },
    {
      id: "freehold_share",
      label: "Proporsi tanah hak milik (ATR/BPN)",
      domain: "household_housing",
      weight: 0.40,
      direction: "positive",
      unit: "%",
    },
    {
      id: "big_slum_presence",
      label: "Kehadiran kawasan kumuh BIG",
      domain: "household_housing",
      weight: 0.20,
      direction: "lower_is_higher_signal",
      unit: "%",
    },
    {
      id: "vehicle_ownership_share",
      label: "Kepemilikan kendaraan",
      domain: "consumption",
      weight: 0.60,
      direction: "positive",
      unit: "%",
    },
    {
      id: "internet_access_share",
      label: "Akses internet",
      domain: "consumption",
      weight: 0.40,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_children_0_14",
      label: "Persentase penduduk usia 0-14",
      domain: "demography",
      weight: 0.35,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_working_age_15_64",
      label: "Persentase penduduk usia produktif 15-64",
      domain: "demography",
      weight: 0.45,
      direction: "positive",
      unit: "%",
    },
    {
      id: "pct_elderly_65_plus",
      label: "Persentase penduduk usia 65+",
      domain: "demography",
      weight: 0.20,
      direction: "lower_is_higher_signal",
      unit: "%",
    },
  ],
  limitations: [
    "Belum menggunakan pendapatan, kemiskinan, kualitas rumah, aset, atau konsumsi karena field tersebut belum tersedia pada payload aktif.",
    "Pendidikan dan pekerjaan dihitung hanya dari field Dukcapil yang tersedia dan memiliki denominator kategori yang dapat dihitung.",
    "A/B/C memakai ambang 40/60 pada indeks 0-100 untuk pembacaan operasional; ini bukan klasifikasi resmi pemerintah.",
    "Skor ini tetap provisional dan bukan klaim SES ekonomi resmi sebelum indikator ekonomi ditambahkan.",
    "Nilai tanah BHUMI menjadi proxy ekonomi/lokasi dan ikut dihitung setelah hexagon diperkaya; ini bukan pengganti pendapatan rumah tangga.",
    "Perumahan formal/padat BHUMI dihitung sebagai Potensi Area; kategori kampung dikeluarkan agar tidak dianggap sebagai perumahan formal.",
    "Komponen demografi memakai proporsi usia 0-14, usia produktif 15-64, dan usia 65+; seluruh persentase kelompok usia tetap disediakan sebagai rincian, tetapi bukan semuanya dijumlahkan sebagai skor terpisah.",
  ],
};
